### ISSUE TITLE
Error: Handler Not Found

### ISSUE THREAD

**Issue by ganeshyedla** [jolocom/interactions-demo#14]
at internals.notFound (/home/ec2-user/interactions-demo/service_agent/node_modules/@hapi/hapi/lib/core.js:632:16)
    at module.exports.internals.Manager.execute (/home/ec2-user/interactions-demo/service_agent/node_modules/@hapi/hapi/lib/toolkit.js:41:33)
    at Object.internals.handler (/home/ec2-user/interactions-demo/service_agent/node_modules/@hapi/hapi/lib/handler.js:46:48)
    at exports.execute (/home/ec2-user/interactions-demo/service_agent/node_modules/@hapi/hapi/lib/handler.js:31:36)
    at Request._lifecycle (/home/ec2-user/interactions-demo/service_agent/node_modules/@hapi/hapi/lib/request.js:312:68)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by clauxx** [comment]
@ganeshyedla Please provide some details in regards to the error. The steps to reproduce it would be very helpful.

**Comment by ganeshyedla** [comment]
I think this is the same issue [https://github.com/devinivy/hapipal-realworld-example-app/issues/4#issuecomment-476002593](url)
It says : You're seeing the "not found" error because the API is in development mode and you went to a route that doesn't exist, probably http://localhost:3000/. Try going to a route that does exist, such as http://localhost:3000/api/tags

**Comment by Muhammad-Altabba** [comment]
Hello @clauxx 
I am facing the same exception whenever I scan the QR code from SmartWallet app.
Steps to reproduce:
- Clone the latest version of this repo.
- Run the frontend and the service_agent.
- Install the latest version of SmartWallet from Google Play
- Scan a QR code from the frontend.
Then an error is shown on the mobile app that says: Whoops... We weren't expecting this to happen either...
And an exception is thrown at the backend that is shown in its console:
```
Debug: handler, error 
    Error: Not Found
    at internals.notFound (/Volumes/Data/repositories/interactions-demo/service_agent/node_modules/@hapi/hapi/lib/core.js:632:16)
    at module.exports.internals.Manager.execute (/Volumes/Data/repositories/interactions-demo/service_agent/node_modules/@hapi/hapi/lib/toolkit.js:41:33)
    at Object.internals.handler (/Volumes/Data/repositories/interactions-demo/service_agent/node_modules/@hapi/hapi/lib/handler.js:46:48)
    at exports.execute (/Volumes/Data/repositories/interactions-demo/service_agent/node_modules/@hapi/hapi/lib/handler.js:31:36)
    at Request._lifecycle (/Volumes/Data/repositories/interactions-demo/service_agent/node_modules/@hapi/hapi/lib/request.js:312:68)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Request._execute (/Volumes/Data/repositories/interactions-demo/service_agent/node_modules/@hapi/hapi/lib/request.js:221:9)
```

As you see the exception comes at the backend so it is reached from the mobile app. However, I also tried accessing with `ngrok` and the same behavior was observed.

So, what do you suggest?
Thanks,

**Comment by Muhammad-Altabba** [comment]
The exception stopped coming without doing any modification. Even though, it was constantly coming over a time span of a couple of days.

I suspect the issue was originated during the DID anchoring (possibly an issue related to the connection to IPFS). However, now the issue is not coming anymore so it is hard to tell.

**Comment by clauxx** [comment]
Hi @Muhammad-Altabba! One reason could be anchoring, as you mentioned, where our Infura node doesn't have enough ETH to register the agent. In that case you would get an issue during the identity creation process of the agent. Not sure what exactly caused it during the interaction request, but LMK if you get that again so we can try to reproduce it.

**Comment by Muhammad-Altabba** [comment]
Hello @clauxx ,
This issue is coming again now and here is more info:
When running the mobile app in the emulator (SmartWallet) in the emulator, it shows: "InvalidToken". And when tracing the exception down further, the internal exception is `DIDNotAnchored`.
